apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: elastic-system
spec:
  encryptedData:
    s3.client.default: AgCTyihDx/x9asoeWbzfYz6vl8OMnPqVN9BpKbZLHHeIZ03IWz+mYg/mxFI8QadzN96ZBgYrZzp7oGJ4ZW5rW+3ioJw966x7qLnCQKWneDd9wnEenltf7sVEbNjlw1UpAgLUaMInF3JSqkwp/ZfJ7FUukc27AzAa7xOcn0wxNg5WB2BfQr4tiEoiwpKA1u3fD3mD8EhkualdzcbN1pmQ6xYS+nOOOMPlDS7gTbyH/zeDgxagITLyjR2o5MTJbdYOIu48gDxPmV0Mc146ZgSUoGHaoMWwYjGoXD09rEIr8Yzv9JEuGpSRb7ZUtNgDuJsklbnOM5TmEq2L0BQocTMZEA9YDZce5zRFSJ2Lg6q80nu/l5mtqQfrBUu82taC601IHTHiqRBGRxuJIabFMzoktEnnpLcR9Hu6EZjrGJEQW2Oa8x0xs4AANRdLmV+MT0EwwQj6tpFjUGT2z3tj6r2UVp2wktDop0A6o/njv84q57gJVeRCdPm7pC5y/hkddzngBig42LGoBpOBzYxmGDxXMW4LpUqpEPiyA2DV+YlZ7oFNFMESilN9j5zhJO3er/C7MY37ujQ1XWIX0awT+eytOP4jw8gjCJMY00bs8i1v2o8zGrXp5vy2+msvsESTEmbElywknRPGgtRPQ0gWApa6IyEJ6xwh7GHL5xZ5FpxBYws0sTI1ZtaoLjLYReHCVm7Xo294Etz0RkZ7KH4zLNA8RxaR4L+s0OKEapT+mL95YFIyU7FEeQeselAhOigZWBXY/7lmWCMuPcnE3YECuhROaqbTA8Al8MpyhYisWv5i3HgS1CTX
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: elastic-system

