apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: snapshot-settings
  namespace: elastic-system
spec:
  encryptedData:
    s3.client.default.access_key: AgAOo8lLbIdnx8Qqain/ViLjQ7rbULk41CVzUL6nicQhLu6Aek8wrEEy5qOBDlhVR6X0/RQHlhyPs3ZCaVXx/5YzcezWnAG08b7js/rNP0bVI+eoP3TOYSLERKdA7SXRKl2TTlYZ/mbCRlsjqLu7UL2aWbTPJ6UqpVVpounb3v52N4ecn5PLNSHStgU0RwtnIZ9WvLsY97uZX/fk3d/2+F4P9zmy+lX6EN8YG0sv+7zUutIfpdRpR7IDKlbSF5jBxqbwSHrVVL2+hM9ZryN+tr+O+4UVn6tO8PlJhAhTdSS1L1P21xyu810mvGeRYV05dZ53Qm5ZyF9UN4oMTPTOI5PcI2z6Ro/g023qa1yFw2l+qGyE58DHQU6nMc4wwLrcy084RZ40vGDbRxqK9tuTH9lGmHPIvQUgnjyKq3zMmkGfOrR1n2+bhPyovUTnUrBVnZ2+jrq5q0Jfrx39QEKpSkXrWu7/dU4+tx+npCH8m83Sdt+5n/OtHUlU9zBXqv7kk3eJqOK02XEMGTqX6Gp261gw8zSdnEbxRfHlt0qFQ/clM9kdZW6AQAbux1MdJTXPxele/EsYVbQGw9hQdLgkO9kWWXCtmNKdx4RN86HCxhh8gJvmeM8nEcp9YTlvahQvJOQk2fx7n12gnPfpSjgGoTTH/VTuX21gvPN3Uw2Of/WyopQ+50jz6e396VLdtm0JNILekW/107KxOj1lP1vPAUFe
    s3.client.default.secret_key: AgBEuEx19baa5fLSnQ1YMwD/bTwz63cGnHExKbVyiqj+7fOvxCu50jS2pYjJBX6MWXFGXF9MoNJqNrauhib4iz2LR4zs7ogDV7M8opoXqa+XLolS4CWFAVpOjcICRgOzcuZo9/xhaYXr4wD3tU4CesC9JTk2Mp4Uq6xMyLJ0NejuNeQ3lyKOlZjp2G0fcQX13fXfGYRswLtMA98RZ0Eh8pvKOeChF/rzaX9vkrpSQPU1+r1bylcZCeR48LyTS5O5tNx8KrBenja3KggrnaqG1RT5QaBz149leCj9WXBwLTvq9eZNirZ83BSCeaQybq5NRVT5OJn8sTzBf2RO70ffznNXGeHK7CDu6MHfLtvpgNyrSV6OpRBTgmCacJT9vNThDOEs89pt63Hl1WsinSF7xGAr21dt1bLLCBJZrA4OLnVlLa5p8DH9V7HK8hsbmlmfj3MFsIMmvl0y/q8zFj3qu2YAkiV/jacly3aPJhYZx93wMJQ9585ZPyMxGlaGuuj4WxY0fURKM+zFN3vBtHDfOOcMex6KdaCGLtAUO+kXyX0VV5VT/xURxnL8LAQfIrqGKacpPaWEaQc4VDKn3p71juE/mi4Bk17ZbnMq/F0tuvoMcGLzTTa6bu5tNbumaV0VueV6b9m7AZA29WfxxumcFNC5fUD30yC96p3+AstbNaQOnTnHh1kn+7vNAXazhSFdZcmy/3u/ig/nAVvqK1gb5zXrIDJfg5I5kYO5HvEay88a8w==
  template:
    metadata:
      creationTimestamp: null
      name: snapshot-settings
      namespace: elastic-system

