apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgCryOsSyeAgbe3H4dLyqyoJcSNugItzlkY+7l6rdV0oPHEKIQFkdohDyjiq/jabUHslTa5TvtqijyZagV91bkCxCOFRkRh9T9VOXXmp6xVMU5pPNsVfY//y2WEnvkPbOn5tET1sPAI4eSISG/p6WmZIOw7xINamyzcg15PPLJs58dJtTI37mlGhPEg4X2Jpn97G29QG21q4WnRUbYa7QO19wIGbJKbeev6DYweDB7SASun+i7QCz0RnIXob1IDyjENY5zLyGGh0m0KqqJ+jzSYUWi9euil1wapWvJsOx/ub3EpbOVMfO35sTk5JwWX/wACw28EpvQMLrcHRtDhE7ckP7UP+vjHm224ENnQqTP9jvO2Cah38+RhZFgWqNWTI9tvdlDVYqRLEnCda7KCDZfDlLTWoaij4VenS6CzQ96P3eUvGXnWVI35uyZdfH4Z0wQ4TOJheMRG/s4u/aFW3S21Tp0E3W5iNDSn5DyX0KaX2G+DfDjYHj04m5AH+MJT4hNF3uA8UmgIedECFINe8dha91f4kw/Vi+EjSYBhm4ItlGeBoQ8fz4ZhGrfPxJzPWBn9oHJBPvI9j//Y6fjGesAbcVpXVvORlMsArsNjE+1GZrLIGqUR7+DDvB/yRGHH9aQQHjXRfAOgBFSDB4dt2E+JriVigLPPH3G4ExUlLGFEmvGEZYmgJ9J9q8eRlCO/vHRQM+HZzOG7Bgld9fpFV5FA=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: kube-system

