apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgCFNNoBdcI/I3rf3zu2OE0kb6/i95GLFa6tRp8HGxktnQ3CmmYnYKK31RwqSXHoC4CYrZCGVfyIdjHuz73SiA9/1yqvwreGddpm9NTpE2jjiWrH+XZWtJiS1fa/38FMHCdEvT8ZAoJBsPxl4URdWE6fHj+/NGAZs7Cl8kuBeimksnovDH2t0dp1ZeSaavz1LxPzZYoJ14TMlBcQXCfHOR//+8o80D8Ee4EYNxaJAu6LGhMGtTYXz4JI9q2MEIW7rMCpydvcRQEwN6+PSmZb33FQnuLx5rqkHwwhmRsbC1MyMrdQOiK+fHntjLryGsJ3/6efP7KLN94JJ9JF6e72HX/0jVNv6xsco5wb4oHEQ1AAz8eggv9vem5sAuSl4iyfvY31gXd+loqE7YWJKOA7B0SMzhSMI0r0X2mka0u0vOscIMU58wci7Ab/XzMxH/xDTNPAfF0Pd97YeKbY4uYGBQHx3W+dQ6tl6loaTj7BUSOhW/TCVAmn3ocOEO8VJSwZFwqbP5aEKQSwOSvf5gCfAQLAxpj/En8ZUhTYg4CM6xw/WkkEM+IkqlxKv6CvRaGsugNkym3vR9n2Xz47Ue54vL6oea5s8CH7rz39itGEwgYjm8ULpnouLO2m0f8JdeR4mgfR4Nmo4apUynVuts8hQnj6PqsX6LkbHtcmO+nm78SBxJry+gedgyjj7ZOoYdZMPy3AYTiCsaRo2Ji0iO9p3bXFYQiPif/3DhSD3dIjVatKhCFcudWTDodT9k9dN60=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: kube-system

